# cSpell Settings

# Version of the setting file.  Always 0.2
"version": "0.2"
# language - current active spelling language
"language": "en-gb"

# words - list of words to be always considered correct
"words":
  [
    "idems",
    "quickstart",
    "glitchtip",
    "mkdocs",
    "venv",
    "linenums",
    "sourcemaps",
    "ionicons",
    "nocheck",
    "sidemenu",
    "templatename",
    "fontawesome",
    "gdrive",
    "lottie",
    "overidden",
  ]
# flagWords - list of words to be always considered incorrect
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the"
"flagWords": ["hte"]

"ignorePaths": ["node_modules/**"]
