# Deploy to firebase hosting on PR merge
# Specifies deployment target based on branch
# Master -> plh_global
# Deployment/{deployment_name} -> {deployment_name}
name: Deployment Hosting
on:
  push:
    branches:
      - deployment/*
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      # Extract deployment name as the slug of target PR branch via string operators, e.g. /deployment/plh_tz -> plh_tz
      # https://www.linuxjournal.com/article/8919, https://github.com/greenbone/gsa/actions/runs/1277581365/workflow
      - name: Set Environment Deployment
        run: |
          echo ${GITHUB_REF##*/}
          if [ "$GITHUB_REF" = "master" ];                              \
          then echo "DEPLOYMENT_NAME=plh_global" >> $GITHUB_ENV;
          else echo "DEPLOYMENT_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV;
          fi;
        shell: bash
      - run: |
          echo $GITHUB_REF
          echo $DEPLOYMENT_NAME
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Set Scripts Deployment
        run: yarn scripts deployment set $DEPLOYMENT_NAME
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLH_TEENS_APP1 }}"
          projectId: plh-teens-app1
          # NOTE - deployment target should be set in firebase.json and .firebaserc
          target: "${{env.DEPLOYMENT_NAME}}"
          channelId: live
      # Known issue - success message does not specify correct deployment url
      # Not used anywhere else so assume fine for now (only gh action output incorrect)
      # https://github.com/FirebaseExtended/action-hosting-deploy/issues/126
