name: Deployment Preview
on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - deployment/*
      - master
  push:
    branches:
      - feat/deployment-preview
jobs:
  build_and_preview:
    if: contains(github.event.pull_request.labels.*.name, 'Test - preview')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - run:  echo "target deployment: ${{ env.GITHUB_HEAD_REF_SLUG }}"
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Set Deployment
        run: yarn scripts deployment set ${{ env.GITHUB_HEAD_REF_SLUG }}
        env:
          APP_DEPLOYMENT_NAME: ${{ secrets.APP_DEPLOYMENT_NAME }}
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLH_TEENS_APP1 }}"
          projectId: plh-teens-app1
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
