name: PR Build
on:
  push:
    branches:
      - none
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Get PR Number
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR Number is $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - name: yarn install
        run: yarn install
      - name: Build Angular for PR
        run: npx ng build --prod --base-href /$PR_NUMBER/ --deploy-url /$PR_NUMBER/
      - name: index.html as 404 page
        run: cp ./www/index.html ./www/404.html
      - name: Deploy to Github pages ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: www
          target-folder: ${{ env.PR_NUMBER }}
          repository-name: IDEMSInternational/parenting-app-ui-pr-preview
          ssh-key: ${{ secrets.PR_GH_DEPLOY_KEY }}
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        env:
          PR_URL: https://plh-pr.idems.international/${{ env.PR_NUMBER }}/index.html
        with:
          status: "success"
          url: ${{ env.PR_URL }}
          description: "Uploaded PR Preview to Github Pages"
          name: "PR Preview"
