# Basic test to ensure PRs pass build. Default runner except when preview deployment already generated
name: Test Build
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/web-build.yml
    secrets: inherit
    with:
      include-tests: true
      skip-upload: true
      # When testing build binary assets not required
      lfs: false 
      deployment: debug