# Generate a set of screenshots on the current branch and store as an artifact for future comparison
name: Test-Visual Generate Screenshots
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test_visual_generate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Start server and generate screenshots
        # Will always throw error even if successful at end as yarn start script terminated abruptly by\
        # concurrently kill after test-visual complete
        continue-on-error: true
        run: |
          npx concurrently --kill-others \
          "yarn start" \
          "npx wait-on http-get://localhost:4200 && yarn workspace test-visual start generate --concurrency 5"
      - name: test
        run: ls packages/test-visual/output/screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots-artifact
          path: packages/test-visual/output/screenshots
          retention-days: 90
          if-no-files-found: error
